apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: producer
    resources: {}
    volumeMounts: #
    - name: sharedvolume # 使用下面 Volumes 的 sharedvolume
      mountPath: /etc/putting # 掛載到 /etc/putting
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: consumer # !
    volumeMounts: #
    - name: sharedvolume # 使用下面 Volumes 的 sharedvolume
      mountPath: /etc/getting # 掛載到 /etc/getting
  volumes: #
  - name: sharedvolume #
    emptyDir: {} #      
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
