apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sec-file-nginx
  name: sec-file-nginx
spec:
  volumes: # specify the volumes
  - name: mysecret # 容器認定的secret名稱
    secret: #
      secretName: sec-file # 前面建立的 secret
  containers:
  - image: nginx
    name: sec-file-nginx
    resources: {}
    volumeMounts: # our volume mounts
    - name: mysecret # name on pod.spec.volumes
      mountPath: /etc/mysecret #our mount path  
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
