apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sec-env-nginx
  name: sec-env-nginx
spec:
  containers:
  - image: nginx
    name: sec-env-nginx
    resources: {}
    env: # 表示以環境變數提供
    - name: USERNAME # 以 USERNAME 作為環境變數的 key
      valueFrom:
        secretKeyRef: # secret reference
          name: sec-file # 之前建立的 filesecret
          key: username # 建立 filesecrect 時使用的 key
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
