apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cmenv-nginx
  name: cmenv-nginx
spec:
  containers:
  - image: nginx
    name: cmenv-nginx
    resources: {}
    env:
    - name: option # 環境變數名稱
      valueFrom:
        configMapKeyRef:
          name: cmenv # configMap 名稱
          key: var1 # name of the entity
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
